### ISSUE TITLE
cbd wont start

### ISSUE THREAD

**Issue by george-vieira** [GreenCom-Networks/centreon-install#3]
Fresh install on xen guest using xen-tools (in case it's too thin in dependencies)

root@centreon:~ $ bash centreon.sh
Debian Jessie

=======================| Install details |============================

                  MariaDB    : 10.1
                  Clib       : 1.4.2
                  Connector  : 1.1.2
                  Engine     : 1.5.0
                  Plugin     : 2.1.1
                  Broker     : 2.11.0
                  Centreon   : 2.7.1
                  Install dir: /usr/local
                  Source dir : /usr/local/src

======================================================================

Step1  => Install PHP, PEAR                                     [ OK ]
Step1  => Install MariaDB                                       [ OK ]
Step3  => Clib install                                          [ OK ]
Step4  => Centreon Perl and SSH connectors install              [ OK ]
Step5  => Centreon Engine install                               [ OK ]
Step6  => Nagios plugins install                                [ OK ]
Step6  => Centreon plugins install                              [ OK ]
Step7  => Centreon Broker install                               [ OK ]
Step8  => Centreon template generation                          [ OK ]
Step9  => Centreon web interface install                        [ OK ]
Step10 => Post install                                          [ OK ]
Step12 => Widgets and Nagvis install                            [ OK ]

Go to http://172.16.200.25/centreon to complete the setup

root@centreon:~ $ /etc/init.d/cbd restart
[ ok ] Restarting cbd (via systemctl): cbd.service.
root@centreon:~ $ ps -ef |grep cbd
root     16526   292  0 18:26 pts/0    00:00:00 grep cbd
root@centreon:~ $

even more strange is the lack of 'etc' config for the broker

root@centreon:~ $ ls -l /usr/local/centreon-broker/etc/
total 4
-rwxrwxr-x 1 centreon-broker centreon-broker 504 Jan 25 17:39 master.run
root@centreon:~ $

I can't see (so far) where in the installer this doesn't generate the config files.

**Comment by albundy83** [comment]
You have used the latest version as yesterday, I have done some work on it. 
Can you connect to the console at least and perform the Web configuration?

**Comment by george-vieira** [comment]
centeon-install.log shows final part of centreon-broker build:
[ 65%] Built target 20-storage
[ 67%] Built target 70-influxdb
[ 68%] Built target 70-graphite
[ 88%] Built target 20-bam
[ 91%] Built target 50-tcp
[ 93%] Built target 60-tls
[ 97%] Built target 80-bbdo
[100%] Built target 80-ndo
Install the project...
-- Install configuration: ""
-- Installing: /etc/default/cbd
-- Installing: /usr/local/centreon-broker/etc/master.run
-- Installing: /etc/init.d/cbd
-- Installing: /usr/local/centreon-broker/bin/cbd
-- Installing: /usr/local/centreon-broker/lib/centreon-broker/15-stats.so
-- Installing: /usr/local/centreon-broker/lib/centreon-broker/10-neb.so
-- Installing: /usr/local/centreon-broker/lib/cbmod.so
-- Installing: /usr/local/centreon-broker/lib/centreon-broker/50-file.so
-- Installing: /usr/local/centreon-broker/lib/centreon-broker/60-compression.so
-- Installing: /usr/local/centreon-broker/lib/centreon-broker/20-correlation.so
-- Installing: /usr/local/centreon-broker/lib/centreon-broker/05-dumper.so
-- Installing: /usr/local/centreon-broker/lib/centreon-broker/70-rrd.so
-- Installing: /usr/local/centreon-broker/lib/centreon-broker/80-sql.so
-- Installing: /usr/local/centreon-broker/lib/centreon-broker/20-storage.so
-- Installing: /usr/local/centreon-broker/lib/centreon-broker/70-influxdb.so
-- Installing: /usr/local/centreon-broker/lib/centreon-broker/70-graphite.so
-- Installing: /usr/local/centreon-broker/lib/centreon-broker/20-bam.so
-- Installing: /usr/local/centreon-broker/lib/centreon-broker/50-tcp.so
-- Installing: /usr/local/centreon-broker/lib/centreon-broker/60-tls.so
-- Installing: /usr/local/centreon-broker/lib/centreon-broker/80-bbdo.so
-- Installing: /usr/local/centreon-broker/lib/centreon-broker/80-ndo.so

Totally unrelated but also to note, errors occurred on widgets. disk isn't full, but can't find src files.

centreon-widget-graph-monitoring-1.3.0/graph-monitoring/resources/centreon-logo.png
centreon-widget-graph-monitoring-1.3.0/graph-monitoring/src/
centreon-widget-graph-monitoring-1.3.0/graph-monitoring/src/generateGraph.php

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
centreon-widget-engine-status-1.0.0/LICENSE
centreon-widget-engine-status-1.0.0/engine-status/

**Comment by george-vieira** [comment]
Gee you're quick, yes the web install worked fine including the auto path (awweesome) but broker etc still empty.

just in case I missed anything important, I've attached the install file.

[centreon-install.log.txt](https://github.com/GreenCom-Networks/centreon-install/files/102897/centreon-install.log.txt)

**Comment by albundy83** [comment]
As I ask you, can you connect to the web console and finish the setup.
The logs you sent to me are clean (even if there was a problem with a widget (but no impact on the installation).
If you can connect to it, finish the setup, apply configuration and restart poller.

**Comment by george-vieira** [comment]
ah yes, sorry I did finish the install but when you said apply configuration I didn't realise you meant the poller but simply doing the paths etc up until the login.

I have apply changes and that seems to have done the trick. I assume you're update may have fixed it as I added a host to yesterdays attempt and applying changes made no difference whereas todays one has but didn't think to try it ;)

You may want to update your readme so it's clear the steps and not to bother with 'service cbd restart' and put a step to login, apply Poller changes and confirm the poller is running or something.

Also, clapi, can't see where this is documented. Want to use it to load my import from my old 2.6.6 as i'm not sure going to 2.7.1 will work without breaking. any docs on how to use the web API ?

**Comment by albundy83** [comment]
Yes, you are right, I will update the documentation.
For clapi, you can check with the official Centreon documenation : 
https://documentation.centreon.com/docs/centreon-clapi/en/latest/import_export.html

For short, you can use this command to export : 
```
/usr/local/centreon/bin/centreon -u <username> -p <password> -e > export.txt
```
And this one to import :
```
/usr/local/centreon/bin/centreon -u <username> -p <password> -i export.txt
```
(That's command I use to dump my Centreon configuration to backup it each night.
But it will not export your collected data (graph, stats etc..)
For the upgrade, I have done it without any problem (I have tested it on debian 7 and 8) but we never know...

**Comment by albundy83** [comment]
Don't forget to update the parameter MYSQL_PASSWORD with your current mysql root user.

**Comment by george-vieira** [comment]
yes, as per my updated commented "(found it)", I just searched for centreon and found that script which seemed to be the one.

regarding the MYSQL_PASSWORD, may I suggest you enforce people to change it by detecting the password not changing and throwing an error (unless people like root password MYSQL_PASSWORD :P )

:+1:  on the script. working really well. might need to explain how to switch the servers role though so instead of a central web server, how to enable a remote poller, etc.
